name: Bailey Robert
favicon: null
layout_spectrum: 0.6597013706341386
typography_spectrum: 0.9353971318341792
title: I was just thinking...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120c0e'
    - '#716b6d'
    - '#badef4'
    - '#94a4b1'
    - '#d29135'
  brandStrength: 0.643742477055639
  lightness: 0.2815050152130425
  saturation: 0.9219227484427392
  rhythmicContrast: 0.33682781108655035
purpose: []
